//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Dicom {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Dicom.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-DICOM, application-level logic exception or execution failure.
        /// </summary>
        public static string ExceptionApplicationLevelLogic {
            get {
                return ResourceManager.GetString("ExceptionApplicationLevelLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AE Title cannot be null.
        /// </summary>
        public static string ExceptionDicomAETitleNull {
            get {
                return ResourceManager.GetString("ExceptionDicomAETitleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AE Title cannot be zero-length.
        /// </summary>
        public static string ExceptionDicomAETitleZeroLength {
            get {
                return ResourceManager.GetString("ExceptionDicomAETitleZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection timeout value must be between 1 and 32767.
        /// </summary>
        public static string ExceptionDicomConnectionTimeoutOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionDicomConnectionTimeoutOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0} - {1}.
        /// </summary>
        public static string ExceptionDICOMFile {
            get {
                return ResourceManager.GetString("ExceptionDICOMFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The find dataset cannot be null.
        /// </summary>
        public static string ExceptionDicomFindDatasetNull {
            get {
                return ResourceManager.GetString("ExceptionDicomFindDatasetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hostname cannot be null.
        /// </summary>
        public static string ExceptionDicomHostnameNull {
            get {
                return ResourceManager.GetString("ExceptionDicomHostnameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hostname cannot be zero-length.
        /// </summary>
        public static string ExceptionDicomHostnameZeroLength {
            get {
                return ResourceManager.GetString("ExceptionDicomHostnameZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The listeningPort must be greater than zero and less than System.Int32.MaxValue.
        /// </summary>
        public static string ExceptionDicomListeningPortOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionDicomListeningPortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The move dataset cannot be null.
        /// </summary>
        public static string ExceptionDicomMoveDatasetNull {
            get {
                return ResourceManager.GetString("ExceptionDicomMoveDatasetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed in dataset is null.
        /// </summary>
        public static string ExceptionDicomNullDataset {
            get {
                return ResourceManager.GetString("ExceptionDicomNullDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATIENT level query using the Study Root Query/Retrieve Information model is invalid.
        /// </summary>
        public static string ExceptionDicomPatientLevelQueryInvalid {
            get {
                return ResourceManager.GetString("ExceptionDicomPatientLevelQueryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory where incoming DICOM objects should be saved does not exist - {0}.
        /// </summary>
        public static string ExceptionDicomSaveDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionDicomSaveDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory where inbound DICOM objects are stored cannot be null.
        /// </summary>
        public static string ExceptionDicomSaveDirectoryNull {
            get {
                return ResourceManager.GetString("ExceptionDicomSaveDirectoryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag: {0} - {1}.
        /// </summary>
        public static string ExceptionDICOMTag {
            get {
                return ResourceManager.GetString("ExceptionDICOMTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer syntax {0} for SOP UID = {1} not supported.  Compressed pixel data cannot be loaded at this time..
        /// </summary>
        public static string ExceptionDicomTransferSyntaxNotSupported {
            get {
                return ResourceManager.GetString("ExceptionDicomTransferSyntaxNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Find failed: operation was cancelled..
        /// </summary>
        public static string ExceptionFindCancelled {
            get {
                return ResourceManager.GetString("ExceptionFindCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Find failed: identifier does not match Sop Class..
        /// </summary>
        public static string ExceptionFindFailedIdentifierDoesNotMatchSOPClass {
            get {
                return ResourceManager.GetString("ExceptionFindFailedIdentifierDoesNotMatchSOPClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Find failed: unable to process..
        /// </summary>
        public static string ExceptionFindFailedUnableToProcess {
            get {
                return ResourceManager.GetString("ExceptionFindFailedUnableToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Find warning: unsupported optional keys..
        /// </summary>
        public static string ExceptionFindPendingWarningUnsupportedOptionalKeys {
            get {
                return ResourceManager.GetString("ExceptionFindPendingWarningUnsupportedOptionalKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Find refused: out of resources..
        /// </summary>
        public static string ExceptionFindRefusedOutOfResources {
            get {
                return ResourceManager.GetString("ExceptionFindRefusedOutOfResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Find refused: Sop Class not supported..
        /// </summary>
        public static string ExceptionFindRefusedSOPClassNotSupported {
            get {
                return ResourceManager.GetString("ExceptionFindRefusedSOPClassNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Accession Number cannot be null.
        /// </summary>
        public static string ExceptionGeneralAccessionNull {
            get {
                return ResourceManager.GetString("ExceptionGeneralAccessionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Accession Number cannot be zero-length.
        /// </summary>
        public static string ExceptionGeneralAccessionZeroLength {
            get {
                return ResourceManager.GetString("ExceptionGeneralAccessionZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object passed is is not of the right type for Equals comparison..
        /// </summary>
        public static string ExceptionGeneralEqualsWrongType {
            get {
                return ResourceManager.GetString("ExceptionGeneralEqualsWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument to CompareTo for the type Uid is not itself of type Uid.
        /// </summary>
        public static string ExceptionGeneralUidCompareToTypeIncorrect {
            get {
                return ResourceManager.GetString("ExceptionGeneralUidCompareToTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DICOM UID format: {0}.
        /// </summary>
        public static string ExceptionGeneralUIDFormat {
            get {
                return ResourceManager.GetString("ExceptionGeneralUIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID cannot exceeed 64 characters: {0}.
        /// </summary>
        public static string ExceptionGeneralUIDLength {
            get {
                return ResourceManager.GetString("ExceptionGeneralUIDLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UID cannot be null.
        /// </summary>
        public static string ExceptionGeneralUidNull {
            get {
                return ResourceManager.GetString("ExceptionGeneralUidNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UID cannot be zero-length.
        /// </summary>
        public static string ExceptionGeneralUidZeroLength {
            get {
                return ResourceManager.GetString("ExceptionGeneralUidZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitsAllocated must be either 8 or 16 (bitsAllocated = {0})..
        /// </summary>
        public static string ExceptionInvalidBitsAllocated {
            get {
                return ResourceManager.GetString("ExceptionInvalidBitsAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitsStored must be greater than zero (bitsStored = {0})..
        /// </summary>
        public static string ExceptionInvalidBitsStored {
            get {
                return ResourceManager.GetString("ExceptionInvalidBitsStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitsStored must be &lt;= BitsAllocated (bitsStored = {0}, bitsAllocated = {1})..
        /// </summary>
        public static string ExceptionInvalidBitsStoredBitsAllocated {
            get {
                return ResourceManager.GetString("ExceptionInvalidBitsStoredBitsAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns must be greater than zero (columns = {0})..
        /// </summary>
        public static string ExceptionInvalidColumns {
            get {
                return ResourceManager.GetString("ExceptionInvalidColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighBit must be greater than zero (highBit = {0})..
        /// </summary>
        public static string ExceptionInvalidHighBit {
            get {
                return ResourceManager.GetString("ExceptionInvalidHighBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighBit must be &lt;= BitsAllocated - 1 (highBit = {0}, bitsAllocated = {1})..
        /// </summary>
        public static string ExceptionInvalidHighBitBitsAllocated {
            get {
                return ResourceManager.GetString("ExceptionInvalidHighBitBitsAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotometricInterpretation must be one of the enumerated values specified in DICOM PS 3.3 (photometricInterpretation = {0})..
        /// </summary>
        public static string ExceptionInvalidPhotometricInterpretation {
            get {
                return ResourceManager.GetString("ExceptionInvalidPhotometricInterpretation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotometricInterpretation must be consistent with the the number of SamplesPerPixel (photometricInterpretation = {0}, samplesPerPixel = {1})..
        /// </summary>
        public static string ExceptionInvalidPhotometricInterpretationSamplesPerPixel {
            get {
                return ResourceManager.GetString("ExceptionInvalidPhotometricInterpretationSamplesPerPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixelData length must be equal to SizeInBytes (pixelDataLength = {0}, sizeInBytes = {1})..
        /// </summary>
        public static string ExceptionInvalidPixelData {
            get {
                return ResourceManager.GetString("ExceptionInvalidPixelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixelRepresentation must be 0 or 1 (pixelRepresentation = {0})..
        /// </summary>
        public static string ExceptionInvalidPixelRepresentation {
            get {
                return ResourceManager.GetString("ExceptionInvalidPixelRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanarConfiguration must be 0 or 1 (planarConfiguration = {0})..
        /// </summary>
        public static string ExceptionInvalidPlanarConfiguration {
            get {
                return ResourceManager.GetString("ExceptionInvalidPlanarConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows must be greater than zero (rows = {0})..
        /// </summary>
        public static string ExceptionInvalidRows {
            get {
                return ResourceManager.GetString("ExceptionInvalidRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SamplesPerPixel must be 1, 3 or 4 (samplesPerPixel = {0})..
        /// </summary>
        public static string ExceptionInvalidSamplesPerPixel {
            get {
                return ResourceManager.GetString("ExceptionInvalidSamplesPerPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series instance UID must not be empty..
        /// </summary>
        public static string ExceptionInvalidSeriesInstanceUID {
            get {
                return ResourceManager.GetString("ExceptionInvalidSeriesInstanceUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SizeInBytes improperly calculated (correct size = {0}, calculated size {1})..
        /// </summary>
        public static string ExceptionInvalidSizeInBytes {
            get {
                return ResourceManager.GetString("ExceptionInvalidSizeInBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP instance UID must not be empty..
        /// </summary>
        public static string ExceptionInvalidSOPInstanceUID {
            get {
                return ResourceManager.GetString("ExceptionInvalidSOPInstanceUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study instance UID must not be empty..
        /// </summary>
        public static string ExceptionInvalidStudyInstanceUID {
            get {
                return ResourceManager.GetString("ExceptionInvalidStudyInstanceUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Transfer Syntax UID cannot be empty..
        /// </summary>
        public static string ExceptionInvalidTransferUID {
            get {
                return ResourceManager.GetString("ExceptionInvalidTransferUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Move failed: operation was cancelled..
        /// </summary>
        public static string ExceptionMoveCancelled {
            get {
                return ResourceManager.GetString("ExceptionMoveCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Move failed: destination unknown..
        /// </summary>
        public static string ExceptionMoveFailedDestinationUnknown {
            get {
                return ResourceManager.GetString("ExceptionMoveFailedDestinationUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Move failed: Identifier does not match Sop Class..
        /// </summary>
        public static string ExceptionMoveFailedIdentifierDoesNotMatchSOPClass {
            get {
                return ResourceManager.GetString("ExceptionMoveFailedIdentifierDoesNotMatchSOPClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Move failed: out of resources (number of matches)..
        /// </summary>
        public static string ExceptionMoveFailedOutOfResourcesNumberOfMatches {
            get {
                return ResourceManager.GetString("ExceptionMoveFailedOutOfResourcesNumberOfMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Move failed: out of resources (sub-operations)..
        /// </summary>
        public static string ExceptionMoveFailedOutOfResourcesSubOperations {
            get {
                return ResourceManager.GetString("ExceptionMoveFailedOutOfResourcesSubOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Move failed: Sop Class not supported..
        /// </summary>
        public static string ExceptionMoveFailedSopClassNotSupported {
            get {
                return ResourceManager.GetString("ExceptionMoveFailedSopClassNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Move failed: unable to process..
        /// </summary>
        public static string ExceptionMoveFailedUnableToProcess {
            get {
                return ResourceManager.GetString("ExceptionMoveFailedUnableToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Move warning: sub-operations completed; one or more failures..
        /// </summary>
        public static string ExceptionMoveWarningSuboperationsCompleteOneOrMoreFailures {
            get {
                return ResourceManager.GetString("ExceptionMoveWarningSuboperationsCompleteOneOrMoreFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null.
        /// </summary>
        public static string ExceptionNullReference {
            get {
                return ResourceManager.GetString("ExceptionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poorly formatted Dicom date range {0}..
        /// </summary>
        public static string ExceptionPoorlyFormattedDateRange {
            get {
                return ResourceManager.GetString("ExceptionPoorlyFormattedDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence queries are not supported at this time (tag path = {0})..
        /// </summary>
        public static string ExceptionSequenceQueriesNotSupported {
            get {
                return ResourceManager.GetString("ExceptionSequenceQueriesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type being set is not compatible with the value representation of the tag..
        /// </summary>
        public static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Value Representatoin (VR)  selected was invalid for the tag..
        /// </summary>
        public static string InvalidVR {
            get {
                return ResourceManager.GetString("InvalidVR", resourceCulture);
            }
        }
    }
}
