//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ProductSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProductSettings defaultInstance = ((ProductSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProductSettings())));
        
        public static ProductSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jL55pMp+3yM7A6LSOywdX1oRfRZd9RvJ")]
        public string Name {
            get {
                return ((string)(this["Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vKfTr+ue1fm9jaIYbfkY5g==")]
        public string VersionSuffix {
            get {
                return ((string)(this["VersionSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQpazixeCBBvq0bzF3/Un/1Jj+VVYb1ASJnvtW5wOq0MkD6q0e5fsBbTSf/1f3YmOupFw9rtXbA=")]
        public string Copyright {
            get {
                return ((string)(this["Copyright"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQpazixeCBD4G1zRA+eXWoOkhHpv4j+3ZFb8u6nTqdHUCrHs03TmjVNqz3nFBQnQrGTwhxAjmuQ2KUyxV" +
            "mBfbg/hLi3m8r0bYKXa9a6foVJlnsKNIF+G9nRcvoS/pdxl06SqZSVpXXPoo8P+nHoZtOSwu/rZQ+O7g" +
            "ZBp2NfiRVvUu+/Sf+jfe+s2Gey9zZNv28ef2/DfG5P7MtZOrs0YUn6l6ypji7hM6Uobeh0b83fWi1VF0" +
            "SiuUqtxmlJXlwaCKXLY+hzItghHh8w/D/nOvL1fMtuTc3nqAcPurWNpJ49wp6gRMZulCfiJaT7/6QR0G" +
            "imZhkIGUYDioGYgg/125UkflJ1URvkAIrGBmEDABT0nMocYNfVQwi9Uk+BCwPiYInCmHtb9g8RG8Y9Ey" +
            "g+vhvtPgggiy0/oIFeaAv1IILMYheeXkT3+cIRiggptUm1W4Sb9OHfEWm4AlaQWc5usJzxBsF6gNAYgP" +
            "xw0xyx+Wayiu+NEPT63XEsMQfhUS1cviALvlPp0qi1Ly9aArwtL3VoHaHXvAdU7b3Tf992f3NA+gDZZT" +
            "ft74DqLZLD0HfP6n4b0uX/hbIBCIn9jzEIS9Nuo03LIUEBC/U/HjiU05Iyx2k+vXZp7NBfI4Wb1aI857" +
            "tLb5oO4Fefmz+G5z+m9XPWgFtWLKosLnt3FrKWizjTVOqkqeadjHGy+8kjlzVHkaBOz2xYqglb3kMO4i" +
            "bmrbEnowwB/87OPySVktJ5+Tud14Lw+WdpL0AFFKB7CdEHE5gfo7xQfhtfHTtHYVZoe1fgsOZnVe5f4f" +
            "p8G9ZoY/D0AEdMMQ06w1A1fTeuuAbjZHmlr9pleeKWlh4us+RMDfy43WC3AX5osQ8mKCEosNj1oJL+uw" +
            "qxp9aXY2x3hGGu53LzyNb8vcJpxAiVfiOrSkjTYVKOtqAkq7B/P5UiNhv9+57hf4m1ZNJjcrfTiXfvrv" +
            "NKipUG2YZABiqRGS4rDczxLKs9u9XUKRG4TmQCdYMqZSqr9TXeT4LSocf76ehOmXaJ294NZqQIULqpQM" +
            "x5/06CEpGU4mrASjd+Fyb/E8ClK8z1pGeXN0M83zfhYNSTF7O6eYJ7gPGuZCQO++HrfgUF1gqrqe9seS" +
            "YDAKaaPeu+UKJe/MCv9833ptWsNqrVSqdQBEfcAJNCFguHftmwctrBVKu/x9g6XLAzOHq9yTB3cxZUGN" +
            "293TX3pzvOf+5xogCZxflYNRD88odHbHNawlVuRyo2Q0WVK4x9qubg6v6Ao3FW+aOPCK6EN19igUwVQ0" +
            "F9FIw0T8pEZgKQ2E0RwDcSXJz6m1IPv/H0/eH2FkNkhy3MUYGZ5kot8QmpKP+zJESsyc9alUVG1evwwG" +
            "9M1JD/p3v3/kbgKihVPumOI2z+X5YqHSFpqbQWhTaX8pLFK9G1v4Tm7H+7vX5696IH9QEV1jXWY5qQBA" +
            "fcI9EMZkt/K6km4IqqA2Hq9KucIJG9Gha65UG97Q1QCoN9hSKJifYdcgxIuQRXvDb+ua+sqVWxlJQxrt" +
            "o41eaNblaSqjnRorNTzlDGg3Pn+ioMrjdThXlSizH7URFNrTylppNvEWvn/pTfoP5LC3JF0A1tKEw/KD" +
            "RubJ2uhhnpj8Hg3+8MF+YMoCCIPW5qAZbzaZIBYI16E9FNKagDHa+6kAY4x55ZNxCKAZBDDqNqI08A6v" +
            "ASS9RACxmyoBaDIzu0YJPf26d5LyrMqxU05/w3Y4pcAMvtTlbqaiofy335PaO3eohGjwd91AUcdlPnYZ" +
            "GSHvv8xEjuhhRKOb9P6B9ZCDg5CE5AGpdhhhazgFRI+hMEMVBPPkcti4rZNS1zpe85toks1rinv2uTQW" +
            "GYJgk8ebBxM4WskpAf18KJarFre6/PpFBxUvIqWkCwysQ5OU3oQrrW7zBfHp6rVVFB54cL/UILt8vn78" +
            "WRIHFBlGmSPaJlQ0H2ua/l2o1gpjw6uKEVO3s8ZXroTKbcD89KkaT5HtIqPL3AB3oDaszvbzw2L22mXv" +
            "L05QhXudrzPEC20yZ7/NcIuQroam+MKWUoL5QeqCwwmk3fV4d4qchFygq9Fj921QRoe4Q==")]
        public string License {
            get {
                return ((string)(this["License"]));
            }
        }
    }
}
